### ISSUE TITLE
Mangle "//" when proxying requests

### ISSUE THREAD

**Issue by vincentbernat** [rancher/websocket-proxy#7]
Hey!

When receiving a requests like `/proxy/https://api.exoscale.ch/compute`, this will be rewritten to `/proxy/https:/api.exoscale.ch/compute`. This is due to the path cleaning done in https://github.com/rancherio/websocket-proxy/blob/master/proxy/proxy.go#L107.

Unless there is some purpose to replacing `////` by a single `/`, I would suggest to not just do that.

**Comment by cjellick** [comment]
Hi @vincentbernat.
Unfortunately, there is an explicit purpose for doing that. The golang reverse proxy doesn't handle something like `http://foo.com/v1//content` the same as it would handle  `http://foo.com/v1/content`. In fact, it sees those requests as malformed and just swallows them.

**Comment by cjellick** [comment]
Oh, forgot to mention that (unfortunaely) we have some legacy (but critical) code that creates badly formed urls like I mentioned above, so that's why we have the path cleaning.

We try to keep all our issues in the rancher repo for prioritization. I'm going to open up an issue for this there. Hopefully we can find a solution to accommodate you, just need to get it properly prioritized.
